title: "Levels of Measurement Vocabulary"
email: nicholas.car@anu.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  This vocabulary defines level of measurement that are classifications that describes the nature of information within the values assigned to variables
baseurl: "/levels-of-measurement" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
